services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: taller3_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment: 
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DB=default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144